# Generated by Django 4.0.6 on 2022-08-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualIncidentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_people', models.IntegerField()),
                ('limit_time', models.CharField(max_length=8)),
                ('job_category', models.CharField(max_length=512)),
            ],
        ),
    ]
