# Generated by Django 4.0.6 on 2022-08-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=128)),
                ('car_type', models.CharField(max_length=256)),
                ('used', models.CharField(max_length=64)),
                ('year_of_manufacture', models.CharField(max_length=8)),
                ('third_discount', models.IntegerField(default=0)),
                ('accident_discounts', models.IntegerField(default=0)),
                ('number_of_accidents', models.CharField(max_length=128)),
                ('number_of_incidents', models.CharField(max_length=128)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bimeuser')),
            ],
        ),
    ]
