# Generated by Django 4.1 on 2022-09-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarCategory',
        ),
    ]
